# Azure build pipeline script
# Add steps that build, run tests, deploy, and more: https://aka.ms/yaml

# This script processes daily and official releases (alpha/beta and final)
# To trigger an official release, add a commit tagged in the form "luxcorerender_v*"
# The "version_string" after the "_" in the tag is used in following steps
# to generate binary names like "luxcorerender-<version_string>-<platform>-..."
# One, and only one, tag in the form "luxcorerender_v*" is needed, 
# otherwise the official release build aborts.

resources:
  containers:
  - container: LinuxContainer
    image: ubuntu:14.04

# variables:
# - group: BuildPipelinesGroup

#trigger:
#  branches:
#    include: ['*']

jobs:
- job: DetectBuildType
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-16.04'
    
  steps:
  - script: ./scripts/azurepipeline/detect-build-type.sh
    displayName: Detecting release type (daily, alpha, beta or final)
    name: setvarStep
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: BlendLuxCore
    displayName: 'Upload github_release_title'
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    
#==========================================================================
# Linux version
#==========================================================================
- job: BlendLuxCoreLinux
  dependsOn: DetectBuildType
  condition: succeeded()
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    version_string: $[ dependencies.DetectBuildType.outputs['setvarStep.version_string'] ]

  container: LinuxContainer

  steps:
  - script: ./scripts/azurepipeline/linux/deps-setup.sh
    displayName: Setting up deps
  - script: ../scripts/azurepipeline/linux/pack.sh
    displayName: Packing BlendLuxCore for Linux
  - script: ../scripts/azurepipeline/linux/pack.sh blender280
    displayName: Packing BlendLuxCore_2.80 for Linux
  # - script: ../scripts/azurepipeline/linux/test.sh
    # displayName: Testing BlendLuxCore
    # condition: ${{ eq(parameters.build, 'standard') }}
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: BlendLuxCore
    displayName: 'Upload BlendLuxCore-<version>-linux64.zip'
    condition: eq(variables['System.PullRequest.IsFork'], 'False')


#==========================================================================
# Windows version
#==========================================================================
- job: BlendLuxCoreWindows
  dependsOn: DetectBuildType
  condition: succeeded()
  timeoutInMinutes: 0
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    version_string: $[ dependencies.DetectBuildType.outputs['setvarStep.version_string'] ]

  steps:
  - script: ./scripts/azurepipeline/windows/deps-setup.cmd
    displayName: Setting up deps
  - script: ../scripts/azurepipeline/windows/pack.cmd
    displayName: Packing BlendLuxCore for Windows
  - script: ../scripts/azurepipeline/windows/pack.cmd blender280
    displayName: Packing BlendLuxCore_2.80 for Windows
  # - script: '../scripts/azurepipeline/windows/test.cmd'
    # displayName: Testing BlendLuxCore
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: LuxCore
    displayName: 'Upload BlendLuxCore-<version>-win64.zip'
    condition: eq(variables['System.PullRequest.IsFork'], 'False')


#==========================================================================
# Preparing for GitHub release
#==========================================================================
# This job deletes "latest" tag from BlendLuxCore repo, so that it is then
# recreated at the current commit by the following release pipeline
# Runs only if:
# - this is a daily build
# - at least one of the build jobs was successful 
# - the pipeline has been triggered by master branch and not by a pull request
# - job: DeleteLatestTag
  # dependsOn: 
  # - DetectBuildType
  # - LuxCoreRenderLinux
  # - LuxCoreRenderWindows
  # # - LuxCoreRenderMacOS
  # variables:
    # version_string: $[ dependencies.DetectBuildType.outputs['setvarStep.version_string'] ]
  # condition: |
    # and
    # (
      # eq(variables['System.PullRequest.IsFork'], 'False'),
      # eq(variables['Build.SourceBranchName'], 'master'),
      # eq(dependencies.DetectBuildType.outputs['setvarStep.version_string'], 'latest'),
      # in(dependencies.LuxCoreRenderLinux.result, 'Succeeded', 'SucceededWithIssues'),
      # in(dependencies.LuxCoreRenderWindows.result, 'Succeeded', 'SucceededWithIssues')
    # )
  # timeoutInMinutes: 0
  # pool:
    # vmImage: 'ubuntu-16.04'
    
  # steps:
  # - task: InstallSSHKey@0
    # inputs:
      # hostName: github.com,140.82.118.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      # sshPublicKey: $(PubKey)
      # sshKeySecureFile: luxcore_id_rsa
  # - script: ./scripts/azurepipeline/delete-latest-tag.sh
    # displayName: Deleting tag to update latest build
